const SORT_PRODUCTS = "SORT_PRODUCTS";
const SET_PRODUCTS = "SET_PRODUCTS";
const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
const PRODUCTS_TO_CART = "ADD_PRODUCTS_TO_CART";
const SET_PRODUCTS_FOR_ACTIONS = "SET_PRODUCTS_FOR_ACTIONS";
export {
  SORT_PRODUCTS,
  SET_PRODUCTS,
  SEARCH_PRODUCTS,
  PRODUCTS_TO_CART,
  SET_PRODUCTS_FOR_ACTIONS,
};
